name: Update Standings
on:
  schedule:
    - cron: '0 */6 * * *' # Elke 6 uur
  workflow_dispatch:      # Voor handmatig starten
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install -r requirements.txt
      - name: Scrape
        run: python scraper.py
      - name: Push
        run: |
          git config --global user.name "Scraper Bot"
          git config --global user.email "bot@github.com"
          git add standings.json
          git commit -m "Update standings" || exit 0
          git push
